<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Label="Package Properties">
		<Title>Noise .NET</Title>
		<Description>An optimized coherent noise library for Perlin and cellular noise.</Description>
		<PackageVersion>1.0.0</PackageVersion>
		<PackageTags>noise</PackageTags>
		<PackageProjectUrl>https://github.com/krubbles/NoiseDotNet</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Copyright>Copyright (c) Miles Oetzel</Copyright>
		<IncludeSource>true</IncludeSource>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
  		<None Include="../README.md" Pack="true" PackagePath="/" />
	</ItemGroup>
</Project>
