on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Pack
      run: dotnet pack --configuration Release --no-build --output .
    - name: Push
      run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
      if: ${{ GITHUB_REF == 'refs/heads/main' }}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}